developer_token: 7nekooPhrBIw5pg14cifFQ
client_id: 196276604747-lo52rk3614anlk0v98e6i39f6c66e37d.apps.googleusercontent.com
client_secret: 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
refresh_token: 1//0642WHdS3P4ObCgYIARAAGAYSNwF-L9IrAGiygYSI_Auacs1fO7KvIganjMPdz2DAkSxQMG_gOoTXjeKDv9EAusiECmql5eXekGY
login_customer_id: '7616507735'
linked_customer_id: '4589649684'
use_proto_plus: true
